# Generated by Django 6.0.2 on 2026-03-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
    ]
