# Generated by Django 5.2.12 on 2026-03-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260324_1828'),
        ('accounts', '0005_auto_20260323_1338'),
    ]

    operations = [
    ]
