# Generated by Django 6.0.2 on 2026-03-06 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SKULL', 'Skull'), ('ZOMBIE', 'Zombie'), ('WITCH', 'Witch'), ('DRAGON', 'Dragon')], max_length=20, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('max_hp', models.PositiveIntegerField(default=20)),
                ('damage', models.PositiveIntegerField(default=1)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('is_boss', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FriendType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PHOENIX', 'Phoenix'), ('SHOOTER', 'Shooter'), ('FAIRY', 'Fairy'), ('HULK', 'Hulk')], max_length=20, unique=True)),
                ('ability', models.CharField(blank=True, default='', max_length=200)),
                ('effect_type', models.CharField(choices=[('HEAL', 'Heal'), ('DAMAGE', 'Damage'), ('SPELL', 'Spell'), ('DEFENCE', 'Defence')], max_length=20)),
                ('effect_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SWORD', 'Sword'), ('ARMOUR', 'Armour'), ('HP_DRINK', 'HP Drink'), ('PHOENIX_FOOD', 'Phoenix Food')], max_length=30, unique=True)),
                ('type', models.CharField(choices=[('WEAPON', 'Weapon'), ('ARMOUR', 'Armour'), ('CONSUMABLE', 'Consumable')], max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('effect', models.CharField(choices=[('HEAL', 'Heal'), ('DAMAGE_BOOST', 'Damage Boost'), ('DEFENCE_BOOST', 'Defence Boost')], max_length=20)),
                ('effect_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(blank=True, choices=[('MAGE', 'Mage'), ('SWORDSMAN', 'Swordsman')], default='', max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('hp', models.PositiveIntegerField(default=100)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('monsters_defeated', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_hp', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WON', 'Won'), ('LOST', 'Lost')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enemy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.enemytype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.friendtype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('player', 'friend')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('player', 'item')},
            },
        ),
    ]
