# Generated by Django 2.2.28 on 2026-03-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_enemytype_name_alter_friendtype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemytype',
            name='can_revive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='drops_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropped_by', to='game.Item'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enemytype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friendtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='playerfriend',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='class_type',
            field=models.CharField(blank=True, choices=[('MAGE', 'Mage'), ('SWORDSMAN', 'Swordsman')], default='MAGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
