# Generated by Django 2.2.28 on 2026-03-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20260307_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='current_node',
            field=models.IntegerField(default=0),
        ),
    ]
