# Generated by Django 2.2.28 on 2026-03-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playerprofile_current_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ending_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
