# Generated by Django 2.2.28 on 2026-03-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playerprofile_current_node'),
        ('game', '0005_auto_20260323_1338'),
    ]

    operations = [
    ]
