# Generated by Django 2.2.28 on 2026-03-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_merge_20260324_1019'),
        ('game', '0005_signpost'),
    ]

    operations = [
    ]
