# Generated by Django 2.2.28 on 2026-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_merge_20260324_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='class_selected',
            field=models.BooleanField(default=False),
        ),
    ]
